### ISSUE TITLE
List all datasets

### ISSUE THREAD

**Issue by ZuzanaMa** [TIS2021-FMFI/dekk#22]
Vypis vsetkych ponukanych datasetov do sekcie vedla mapy, v ktorej je mozne scrollovat. 
Datasety by mali byt zoradene podla nejako kluca (idealne podla abecedy) - tato sekcia bude sluzit na to, ze ked pride pouzivatel , ktory nevie ake datasety ho zaujimaju, tak si rovno moze pozriet ake su k dispozicii 

_poznamka k implementacii: v DB tabulka dataset-types_

**Comment by Achinys-out** [comment]
all datasets listed in dropdown, and sorted in alphabeticall order
