### ISSUE TITLE
Correlation Calculation

### ISSUE THREAD

**Issue by ZuzanaMa** [TIS2021-FMFI/dekk#26]
Implementuj funkciu, ktora dostane na vstup 2 datasety a vrati vypocitanu hodnotu.

- [x] implementuj funkciu  backend/frontend - vyplnie z navrhu
- [x] dopln volanie fukncie
- [x] vypis pre pouzivatela ci vypocitana korelacia je signifikatna alebo nie

**Comment by ZuzanaMa** [comment]
Vypocet bude na backende - python script (python obsahuje uz predprogramovane potrebne funkcie)

1. normality test https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.normaltest.html
2. podla vysledku testu sa spusti pearsons (normality test passed) alebo spearmans (normality test did not pass) https://realpython.com/numpy-scipy-pandas-correlation-python/
3. vypocita sa sklon priamky, ktora bud vykreslena pre pouzivatela (info k clanku vyssie)
4. ako spustit z laravelu python script: https://www.sandervanhooft.com/blog/laravel/how-to-use-laravel-with-python-and-the-command-line/
5. posle sa naspat pouzivatelovi uz iba korelacny koeficient a udaje o priamke
6. v js sa vykresli graf aj s priamkou a pouzivatel dostane komentar ohladom korelacneho koeficientu

**Comment by ZuzanaMa** [comment]
another normality test:
https://towardsdatascience.com/normality-tests-in-python-31e04aa4f411

**Comment by ZuzanaMa** [comment]
![Figure_1](https://user-images.githubusercontent.com/73612519/145709389-22a9ca53-e428-435c-a3fd-da9851df9298.png)
output z .py programu

**Comment by sinthoras50** [comment]
@ZuzanaMa 
Dorobil som vypis popisku korelacie pod grafom -> implementacia sa nachadza v graph module pod funkciou print correlation ak by si chcela menit ten vypis.

**Comment by Achinys-out** [comment]
vypocitava sa linearna korelacia, vypise sa o aku korelaciu sa jedna, zaznaci sa v grafe... funguje
