### ISSUE TITLE
Year bar

### ISSUE THREAD

**Issue by ZuzanaMa** [TIS2021-FMFI/dekk#28]
Add year bar -> for choosing the year of datasets. Deafult is the latest year, for which we have data

**Comment by Achinys-out** [comment]
slider pre rok pridany, hodnota z neho je pristupna (check console.log pri posune roku)

**Comment by Achinys-out** [comment]
slider sa upravuje automaticky pri vybere datasetov, automaticky berie intersekciu dvoch alebo len rozmedzie jedneho (podla toho ci je vybrany jeden alebo dva datasety) a nastavi sa na maximalny rok, pre ziadny vybrany dataset sa slider nastavi na 1990-aktualny rok...
