### ISSUE TITLE
Sequence diagram

### ISSUE THREAD

**Issue by ZuzanaMa** [TIS2021-FMFI/dekk#38]
Nakreslit sequence diagram pre vyber datasetov pouzivatelom a nasledne zobrazenie na mape a grafe

**Comment by Achinys-out** [comment]
nakresleny je, vyzera ze v navrhu su s tym ok, jedina zmena po ich review bola  v prvom kroku diagramu: "2 datasets picked" na "1 or 2 datasets picked" kedze to bude fungovat aj pre jeden dataset (vykreslenie jednou farbou)
