### ISSUE TITLE
Prerobit frontend

### ISSUE THREAD

**Issue by ZuzanaMa** [TIS2021-FMFI/dekk#53]
upravit html + dorobit css pre stranku, podla navrhu GUI

**Comment by Achinys-out** [comment]
css pre legendy farieb aby boli pri sebe, upraviť štýl

**Comment by Achinys-out** [comment]
upraviť margin, 
pravú stranu s grafom zúžiť a spraviť viac priestoru pre mapku, 
legendy v mapke vedľa seba horizontálne

**Comment by Achinys-out** [comment]
done

**Comment by Achinys-out** [comment]
prerobene podla poziadaviek zadavatela, opravene chyby v margine, prekryvani slidera, responzivity, fixnuta vyska a sirka pri nacitani webu, farby koresponduju s farbami DEKK institutu
