### ISSUE TITLE
Katalog poziadaviek

### ISSUE THREAD

**Issue by ZuzanaMa** [TIS2021-FMFI/dekk#7]
- [x] urobit kostru katologu
- [x] ku kazdej casti v bodoch popisat co tam bude
- [x] zrevidovat body
- [x]  prepisat do viet

**Comment by pavelpetrovic** [comment]
[katalog_poziadaviek4_editovany.docx](https://github.com/TIS2021-FMFI/dekk/files/7455500/katalog_poziadaviek4_editovany.docx)
